# Generated by Django 4.1.3 on 2022-12-12 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PetProduct',
            new_name='FarmProduct',
        ),
    ]
